###
GET http://localhost:8080/api/bookmarks

###
POST http://localhost:8080/api/bookmarks
Content-Type: application/json

{
  "categoryName": "spring",
  "title": "Spring Website",
  "url": "https://spring.io"
}